version: "3"
services:
  pg_payment:
    image: postgres
    container_name: pg_payment
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=test
    volumes:
      - ./volumes/docker/postgres/:/var/lib/postgresql/data/